#include <stdio.h>

int main(){
    /*CARICA GRAFO IN MEMORIA*/

    /*CALCOLA LA DISTANZA TRA OGNI COPPIA DI NODI, E SALVA QUELLA MAGGIORE*/
    /*NEL MOMENTO IN CUI TROVI 2 NODI CHE NON HANNO UN CAMMINO, STAMPA -1 ED ESCI*/

    /*DEALLOCA GRAFO*/
}