#include <stdio.h>


int main(){
    /*ACQUISISCI n E POI n INTERI, INSERENDOLI IN CODA AD UNA LISTA*/
    /*PER OGNI ELEMENTO NELLA LISTA*/
        /*CALCOLA SOMMA DEI SUCCESSIVI (0 SE NULL)*/
        /*SOSTITUISCI VALORE ELEMENTO CON SOMMA SUFFISSA*/
    /*FREE DELLA LISTA*/
    return 0;
}