#include <stdio.h>

int main(){
    /*CARICA GRAFO IN MEMORIA*/

    /*SE IL GRAFO NON E' CONNESSO, STAMPA -1 ED ESCI*/
    /*ALTRIMENTI STAMPA IL DIAMETRO(IL PIU LUNGO CAMMINO MINIMO TRA 2 NODI DISTINTI DEL GRAFO)*/

    /*DEALLOCA GRAFO*/
}